sources:
    dir: '{root}/sources'
    repos:
        odoo:
            url: https://github.com/odoo/odoo.git
            branch: 9.0
            method: setup
addons:
    config: '__openerp__.py'
reports:
    dir: '{root}/reports'
snapshots:
    dir: '{root}/snapshots'
server:
    config: '{root}/etc/odoo-server.conf'
logging:
    version: 1
    formatters:
        simple:
            format: '%(asctime)s:%(name)s:%(levelname)s:%(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: ERROR
            formatter: simple
            stream: ext://sys.stdout
        file:
            class: logging.FileHandler
            level: DEBUG
            formatter: simple
            filename: '{root}/log/odooenv.log'
    loggers:
        odooenv:
            level: DEBUG
            handlers: [console, file]
            propagate: no
    root:
        level: DEBUG
        handlers: [console]
